// frontend/react/src/App.tsx
import { useState } from 'react';

function App(): JSX.Element {
  const [count, setCount] = useState(0);

  function incrementCount() {
    setCount(count + 1);
  }

  function decrementCount() {
    setCount(count - 1);
  }

  return (
    <>
      <h1>hello</h1>
      <p>{count}</p>
      <button type="button" onClick={incrementCount}>
        +
      </button>
      <button type="button" onClick={decrementCount}>
        -
      </button>
    </>
  );
}

export default App;

// frontend/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0);

function incrementCount() {
  count.value += 1;
}

function decrementCount() {
  count.value -= 1;
}
</script>

<template>
  <h1>hello</h1>
  <p>{{ count }}</p>
  <button type="button" @click="incrementCount">+</button>
  <button type="button" @click="decrementCount">-</button>
</template>

<style scoped></style>
